<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>StructureHandler</AssemblyName>
    <Product>Structure Handler</Product>
    <Version>1.2.6</Version>
    <LangVersion>latest</LangVersion>
    <RootNamespace>StructureHandler</RootNamespace>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModdingTools\ModdingTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\Silverpine_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Silverpine_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Silverpine_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
